### ISSUE TITLE
Reorganisation, Optimization & Batch ToDo

### ISSUE THREAD

**Issue by Konrad1991** [ComPlat/Thermosimfit#12]
## Reorganisation

- [x] seperate App files into server and UI file
- [x] remove add_info (reactive value) and instead use return value of opti
- [x] create separate download function which creates excel file with the returned stuff from opti
- [x] replace req with rwn where possible

## opti function

- [x] add correct names to data.frame results
- [x] add correct names to metrices
- [x] modify plotting accordingly
- [x] return also lower bounds, upper bounds, additionalParameters, npop, ngen, Topology

## batch function

- [x] add a num_rep argument
- [x] define the 3 seed strategies
- [x] loop over num_rep * number of datasets
- [x] store each seed

### make good plots visualising the entire result; dataset differences and replication of dataset differences

- [x] plot states --> measured Signal plot is missing
- [x] plot metrices
- [x] plot parameter
- [x] adapt IDA batch code accordingly
- [x] test App single run IDA
- [x] test App batch run IDA
- [x] change everywhere the check for length = 4 to a reactive value as for the batch process
- [x] check seed setting in promises
