### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Konrad1991** [ComPlat/Thermosimfit#9]
## When choosing model

- [x] Below the tabs at the sidebar: In case you need more information see: https://suprabank.org/glossary

## Website has to be loaded again 

- [x] issue fixed by commit: bc44c38 

## Upload file

- [x] description larger font size; maybe colour; highlighten

## new default values:

- [x] random topology 
- [x] 1000 generation
- [x] lower boundaries Ka_xy to 10
- [x] upper boundaries all to 10^8

## Advice to calc IHD:
- [x] Add to upper boundary cell: IHD * conc ≈ Signal 

## General stuff

- [x] question mark at boundaries and at the results. Hovering tips. Two optimizations. First with wide boundaries. Afterwards chose narrow boundaries based on the result of the first optimization. 
- [x] Rename cancel into stop optimization
- [x] Rename error to error of Signal 

## Seed

- [x] add possibility to set seed

## Testing

- [x] define test for each case (Optimization)
- [x] define test for each case (Sensitivity)
- [x] make screenshot
 
## Result file

- [x] drop down menu: excel, csv; csv without plots; excel with plots
- [x] experimental input data above columns a and b 
- [x] simulation results above the other columns
- [x] add a note about which model was used
- [x] add lb, ub, additional information, pso hyperparameters, seed and OS information (> Sys.info()), R Version (R.Version); tsf version ( packageVersion("tsf")) 
- [x] use correct names
- [x] add unit [M]
